filter:
    excluded_paths: [system/library/vendor/*]

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [system/library/vendor]