language: php

php:
  - 5.4

before_script:
  - git submodule update --init --recursive
  - composer install --dev
  - php -S localhost:8000 -t public &

script: phpunit --configuration tests/travis/sqlite.travis.xml --coverage-text