language: php

php:
  - 5.4
env:
  - DB=sqlite

before_script:
  - mkdir system/logs
  - chmod -R 0777 system/logs
  - mkdir system/data/database
  - chmod -R 0777 system/data/database
  - mkdir system/template
  - composer install --dev
  - php -S 127.0.0.1:8000 -t public &

script: phpunit --configuration sqlite.travis.xml --coverage-text